# Generated by Django 5.1.1 on 2024-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=120)),
                ('avaible', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'LibraryBook',
                'ordering': ['author'],
                'permissions': [('can_view_author', 'Can view author')],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
